### ISSUE TITLE
Seite bleibt hängen

### ISSUE THREAD

**Issue by kremin** [youonlyliveonce/24-1.studio#1]
Die Seite bleibt immer wieder "hängen", d.h. man kann nicht mehr zwischen den Sektionen wechseln. Leider habe ich noch keinen Weg gefunden das zu reproduzieren. Kommt bei mir aber verhältnismässig oft vor. Passiert gefühlt wenn man sehr schnell durch die Sektionen scrollt und nicht wartet.

**Comment by kremin** [comment]
Ist mir nur einmal bis jetzt passiert. Ich checke da nochmal die performance am stressklicken liegt es jedenfalls nicht,

**Comment by Matteng123** [comment]
habe gerade nochmal getestet. also das kommt vor allem beim schnellen scrollen mit der maus vor (mightymouse) - dann bleibt die seite meistens nach der "bilder" sektion hängen. dann geht auch nix mehr. trackpad klappt besser...

habe das gefühl, daß da irgendwas "zuläuft" ...

**Comment by Matteng123** [comment]
closed
