### ISSUE TITLE
Mobil: Preisliste

### ISSUE THREAD

**Issue by kremin** [youonlyliveonce/24-1.studio#5]
Mobil: Preisliste sieht nicht gut aus wegen ungünstiger umbrüche -> Wahrscheinlich auch ne Pflegefrage, aber wahrscheinlich muss man es einmal richten damits zukünftig passt

**Comment by kremin** [comment]
hmm schwer zu richten. Kann die Font kleiner machen oder man spart sich die 10h und schreibt die als Text unter die Tabelle. Tagesmiete sind 10h.

**Comment by Matteng123** [comment]
Dann mach doch mobil die Font für Tabellen kleiner. Finde ich ok. Ist glaube ich die einzige Stelle, wo wir Tabellen haben

**Comment by Matteng123** [comment]
kann geschlossen werden.
